# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  my_job:
    runs-on: ubuntu-latest
    container:
      image: akamai/shell
    steps:
         - name: Log the node version
           run: |
             echo -e "[papi]\nclient_secret = ${{ secrets.AKAMAI_DEFAULT_CLIENT_SECRET }}\nhost = ${{ secrets.AKAMAI_DEFAULT_HOST }}\naccess_token = ${{ secrets.AKAMAI_DEFAULT_ACCESS_TOKEN }}\nclient_token = ${{ secrets.AKAMAI_DEFAULT_CLIENT_TOKEN }}" > "$HOME/.edgerc"
             akamai pm np -e config-rapid-dj.xml -p dj-config-rapid-dj.xml -g grp_178772 -a B-C-1ED34DK
