# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tabs
  workflow_dispatch:
jobs:
  my_job:
    runs-on: ubuntu-latest
    container:
      image: deepakjd2004/github-action
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Terraform - Import an existing property
        run: |
             mkdir output
             cd output
             echo -e "[default]\nclient_secret = ${{ secrets.AKAMAI_DEFAULT_CLIENT_SECRET }}\nhost = ${{ secrets.AKAMAI_DEFAULT_HOST }}\naccess_token = ${{ secrets.AKAMAI_DEFAULT_ACCESS_TOKEN }}\nclient_token = ${{ secrets.AKAMAI_DEFAULT_CLIENT_TOKEN }}\naccount_key = ${{secrets.AKAMAI_AS_ACCOUNTSWITCHKEY}}" > "$HOME/.edgerc"
             akamai terraform --accountkey ${{secrets.AKAMAI_AS_ACCOUNTSWITCHKEY}} create-property Devops-Training
      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@devel
        env:
          API_TOKEN_GITHUB: ${{ secrets.AKAMAI_GITHUB_TOKEN }}
        with:
          source-directory: output/
          destination-github-username: 'deepakjd2004'
          destination-repository-name: 'github-action-terraform'
          user-email: deepakjd2004@gmail.com
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: main
      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
      - name: Checkout Remote directory
        uses: actions/checkout@v3
        with:
          repository: 'deepakjd2004/github-action-terraform'
      - name: Run Import Command
        run: |
              chmod +x import.sh
              ./import.sh
